# This is a basic workflow to help you get started with Actions

name: Cut Audio M3

# Controls when the action will run. 
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: FedericoCarboni/setup-ffmpeg@v1-beta
        id: setup-ffmpeg
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Python deps
        run: pip install -r requirements.txt
      - name: git identity
        run: |
          git config user.email "adam.kariv@gmail.com"
          git config user.name "Adam Kariv"
      - name: cut-audio
        env:
          AIRTABLE_APIKEY: ${{ secrets.AIRTABLE_APIKEY }}
        run: python tools/extract_audio_files.py
