# This is a basic workflow to help you get started with Actions

name: Deploy

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '10'
      - uses: actions/setup-python@v2
        with:
          python-version: '3.7'
      - name: requirements
        run: |
          npm install &&\
          pip install jinja-cli
      - name: git identity
        run: |
          git config user.email "adam.kariv@gmail.com"
          git config user.name "Adam Kariv"
      - name: build
        run: |
          git checkout master
          (git branch -D dist || true)
          git checkout -b dist
          rm .gitignore
          npm run prod
          mkdir dist/atlas-medliq/water-above-water-below
          mkdir dist/atlas-medliq/speculative-tourism-sea-change
          mkdir dist/atlas-medliq/troubled-waters-the-nile-conflict
          jinja -d data/social-m1.json -o dist/atlas-medliq/water-above-water-below/index.html dist/atlas-medliq/index.html
          jinja -d data/social-m2.json -o dist/atlas-medliq/speculative-tourism-sea-change/index.html dist/atlas-medliq/index.html
          jinja -d data/social-m3.json -o dist/atlas-medliq/troubled-waters-the-nile-conflict/index.html dist/atlas-medliq/index.html
          jinja -d data/social-main.json -o dist/atlas-medliq/index-soc.html dist/atlas-medliq/index.html
          mv dist/atlas-medliq/index-soc.html dist/atlas-medliq/index.html
          cp dist/atlas-medliq/index.html dist/atlas-medliq/404.html
          cp CNAME dist/atlas-medliq/
      - name: deploy
        env:
          AIRTABLE_APIKEY: ${{ secrets.AIRTABLE_APIKEY }}
        run: |
          git add dist/atlas-medliq && \
          git commit -m dist && \
          (git branch -D gh-pages || true) && \
          git subtree split --prefix dist/atlas-medliq -b gh-pages && \
          git push -f origin gh-pages:gh-pages && \
          git checkout master && \
          git branch -D gh-pages && \
          git branch -D dist && \
          git checkout . && \
          git push        
