# This is a basic workflow to help you get started with Actions

name: Push audio from Airtable to S3

# Controls when the action will run. 
on:
  workflow_run:
    workflows: ["Cut Audio M3"]
    types:
      - completed

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Python deps
        run: pip install -r requirements.txt
      - name: push-audio
        env:
          AIRTABLE_APIKEY: ${{ secrets.AIRTABLE_APIKEY }}
          BUCKET_NAME: ${{ secrets.BUCKET_NAME }}
          ACCESS_KEY: ${{ secrets.ACCESS_KEY }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
        run: python tools/push_audio_to_s3.py
